language: python

python:
    - "3.6"

env:
    global:
        - CODECOV_TOKEN="e5e426ed-a4c9-43d9-8a98-d549e370578c"

install:
    - pip install -r test_requirements.txt

before_script:
    - py.test api/tests/ --cov=api

script:
    - py.test tests/

after_success:
    - coveralls
